version: '3'
services:
  smd:
    build: .
    environment:
      - DEBUG=1
    volumes:
      - ./:/app
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./src/web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:8000
